### PR TITLE
Fix typos, fix mentions of MP3::ID3Lib instead of MP3::Info

### PR DESCRIPTION
**Pull request by choroba**

### CODE REVIEW

**Comment by davorg** [comment]
Well, that's weird. I wondered how those typos went undetected for so long - but it turns out it's because the module never got released to CPAN.

I'll fix that later today.

Thanks.

**Comment by choroba** [comment]
> never got released to CPAN

In fact, I can find some older versions in BackPAN: https://metacpan.org/release/DAVECROSS/AudioFile-Info-MP3-Info-v1.5.0
🤷🏽

**Comment by davorg** [comment]
Very weird. I have no idea what I was thinking :-/

**Comment by davorg** [comment]
Released as 1.5.1 - https://metacpan.org/release/DAVECROSS/AudioFile-Info-MP3-Info-v1.5.1

Thanks for catching that. I still have no idea why it vanished from CPAN like that.

**Pull request merged**
